---
namespace: kafka-cluster

stack:
  defines: process-group
  metadata:
    name: Apache Kafka
    description: |
      Apache Kafka is an open-source distributed streaming platform designed to handle high-throughput, fault-tolerant, and real-time data processing. 
      It was developed at LinkedIn and later became an Apache Software Foundation project. Kafka is built around a publish-subscribe messaging model and is designed to handle massive amounts of data in real-time. 
      It provides a distributed, fault-tolerant, and scalable architecture that allows data to be ingested, stored, and processed by multiple applications or systems simultaneously.
    tags: streaming,data, analytics, integration, distributed, partitions, message broker, message queue,
    website: https://kafka.apache.org/
    source: https://github.com/apache/kafka
    publisher: monk.io
    icon: https://assets.monk.io/icons/kafka.png
    private: false
  runnable-list:
    - kafka-cluster/zookeeper-1
    - kafka-cluster/kafka-1
    - kafka-cluster/kafka-2
    - kafka-cluster/kafka-3
  variables:
    kafka-image-tag: 7.2.1
    zookeeper-image-tag: 7.2.1
